import { type SidebarsConfig } from "@docusaurus/plugin-content-docs"

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	cliSidebar: [
		{
			type: "autogenerated",
			dirName: "cli"
		}
	],
	sdkSidebar: [
		{
			type: "autogenerated",
			dirName: "sdk"
		}
	],
	apiSidebar: [
		{
			type: "autogenerated",
			dirName: "api"
		}
	],
	desktopSidebar: [
		{
			type: "autogenerated",
			dirName: "desktop"
		}
	],
	webSidebar: [
		{
			type: "autogenerated",
			dirName: "web"
		}
	]
}

export default sidebars
